//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcTusService.TuesdayModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShareWeiEntities : DbContext
    {
        public ShareWeiEntities()
            : base("name=ShareWeiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_reward> tb_reward { get; set; }
        public DbSet<tb_reward_Template_imp> tb_reward_Template_imp { get; set; }
        public DbSet<tb_rewardTemplate> tb_rewardTemplate { get; set; }
        public DbSet<tb_share> tb_share { get; set; }
        public DbSet<tb_task> tb_task { get; set; }
        public DbSet<tb_taskExecute> tb_taskExecute { get; set; }
        public DbSet<tb_taskItem> tb_taskItem { get; set; }
        public DbSet<tb_user> tb_user { get; set; }
        public DbSet<tb_userShare> tb_userShare { get; set; }
    }
}
