
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WcTusService.TuesdayModel
{

using System;
    using System.Collections.Generic;
    
public partial class tb_continuousShare
{

    public int pk_continuousShare_Id { get; set; }

    public int fk_user_Id { get; set; }

    public int fk_task_Id { get; set; }

    public int fk_taskItem_Id { get; set; }

    public bool bit_execute { get; set; }

    public System.DateTime dtm_action { get; set; }

    public System.DateTime dtm_end { get; set; }

    public int int_interval { get; set; }

    public Nullable<System.DateTime> dtm_execute { get; set; }

    public int int_order { get; set; }

}

}
