//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcTusService.TuesdayModel
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    [DataContract]
    public partial class tb_task
    {
        [DataMember]
        public int pk_task_id { get; set; }
        [DataMember]
        public string nvr_taskName { get; set; }
        [DataMember]
        public System.DateTime dtm_createTime { get; set; }
        [DataMember]
        public System.DateTime dtm_actionTime { get; set; }
        [DataMember]
        public System.DateTime dtm_endTime { get; set; }
        [DataMember]
        public bool bit_isDelete { get; set; }
        [DataMember]
        public bool bit_status { get; set; }
        [DataMember]
        public bool bit_inherit { get; set; }
        [DataMember]
        public int fk_share_id { get; set; }
    }
}
