
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WcTusService.TuesdayModel
{

using System;
    using System.Collections.Generic;
    
public partial class tb_taskExecute
{

    public int pk_taskExecute_id { get; set; }

    public int fk_taskItem_id { get; set; }

    public int fk_user_id { get; set; }

    public System.DateTime dtm_executeTime { get; set; }

    public bool bit_isApply { get; set; }

    public Nullable<System.DateTime> dtm_ApplyTime { get; set; }

    public bool bit_isGrant { get; set; }

    public Nullable<System.DateTime> dtm_grantTime { get; set; }

    public bool bit_isDelete { get; set; }

    public int fk_shareContents_id { get; set; }

}

}
