
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WcTusService.TuesdayModel
{

using System;
    using System.Collections.Generic;
    
public partial class tb_token
{

    public int pk_tokenID { get; set; }

    public string vr_appid { get; set; }

    public string vr_token { get; set; }

    public System.DateTime dtm_tokenTime { get; set; }

}

}
