
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace WcTusService.TuesdayModel
{

using System;
    using System.Collections.Generic;
    
public partial class tb_user
{

    public int int_user_id { get; set; }

    public string vr_Tuesday { get; set; }

    public string nvr_userName { get; set; }

    public string vr_phoneNum { get; set; }

    public string vr_wxOpenID { get; set; }

    public string nvr_wxName { get; set; }

    public bool bit_isdelete { get; set; }

}

}
